name: tugas1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/image/ic_launcher.png
  android: true
  ios: true
  web: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: scaleAspectFill
  web_image_mode: center

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/nagarevisi.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/image/ic_launcher.png"
